### ISSUE TITLE
Example # 2 Round spinner has transparent dots

### ISSUE THREAD

**Issue by tylik1** [MatejKustec/SpinThatShit#3]
Hi
https://matejkustec.github.io/SpinThatShit/
If you stop animation for the second preloader, you can find 2 white dots. They are almost invisible with this color scheme, but on other color schemes, are more visible (
Couldn't find the way to fix that.
border-radius + border-top-color compose this bug.

**Comment by MatejKustec** [comment]
Hello, I can confirm that I'm also seeing this bug in Chrome, but when I tried to reproduced on [codepen](http://codepen.io/anon/pen/KaRGGQ) with same properties I couln't see it. Can you check that codepen and let me know, if you still see this? This could be also some browser rendering issue.

Here is screenshot from Safari and Chrome. Safari is OK, but Chrome is not.

![screen shot 2017-02-03 at 21 10 01](https://cloud.githubusercontent.com/assets/5469945/22606770/62dafb6c-ea55-11e6-810b-b18173faf401.png)

**Comment by tylik1** [comment]
Hi, yep i also can't see it in codepen. Really strange, maybe associated with iframe.
I also noticed, that if you reduce border opacity to 0.2 in original demo, the white dots are almost invisible on spin, though if you stop animation it's still there. That'll do as a temporary workaround :)
