### ISSUE TITLE
calling mixing twice with weird behavior: First mixing call uses vars from the second mixing call

### ISSUE THREAD

**Issue by upstroke** [MatejKustec/SpinThatShit#4]
when calling the mixing on a second element, the first element uses the arguments given by the second mixing call.

Example:
```
.rs-btn--primary,
.rs-btn--secondary {
  &.rs-btn--spinner {
    text-indent: -99999px;

    &:after {
      @include loader07($size: 6px, $duration: 1s, $align: middle, $color: white);
      content: "";
      position: absolute;
      margin: -3px auto 0 -3px;
      left: 50%;
      top: 50%;
    }

    > * {
      display: none;
    }
  }
}
```

```
.rs-btn--secondary {
  &.rs-btn--spinner:after {
    @include loader07($size: 6px, $duration: 1s, $align: middle, $color: green);
    margin: -3px auto 0 -3px;
    left: 50%;
    top: 50%;
  }
}
```

I want the button ".rs-btn--primary" with a white spinner and the second button ".rs-btn--secondary" with a green color.
But both buttons (".rs-btn--primary" and ".rs-btn--secondary") result in a spinner with a green color.
I guess this is a SASS bug?

**Comment by MatejKustec** [comment]
Hi, this isn't SASS bug, there is a problem with `@keyframe` names because they are always using same name, so when you call same mixin twice it's always using same `@keyframe` name. I'll try to fix this by end of the week, I'm probably going to try to generate random id on mixin call or add some parameter for animation name.

**Comment by upstroke** [comment]
I See. I trink adding a Name to the Mixing call would be the best solution avoiding misunderstandings or surprises ;-)
